### ISSUE TITLE
Implicit gir1.2-gtk-3.0 runtime dependency

### ISSUE THREAD

**Issue by wgreenberg** [ptomato/jasmine-gjs#18]
Looks like `imports.format`, used by `command.js` has a dependency on Gtk somewhere down the line:

```
gjs> imports.format
typein:1: strict warning: reference to undefined property imports.format
resource:///org/gnome/gjs/modules/format.js:3: strict warning: reference to undefined property imports.gi
resource:///org/gnome/gjs/modules/overrides/GLib.js:258: strict warning: reference to undefined property this.Variant
Error: Requiring GjsPrivate, version none: Typelib file for namespace 'Gtk', version '3.0' not found
```

As such, running jasmine requires Gtk, so it should probably be listed as a debian runtime dependency

**Comment by emerinohdz** [comment]
I'm bumping this, since it is causing problems with a fresh install of GJS obtained through jhbuild.

**Comment by ptomato** [comment]
Unfortunately this is harder than it looks. In order to stop GJS from linking to GTK, we need to solve https://bugzilla.gnome.org/show_bug.cgi?id=773230

**Comment by ptomato** [comment]
That bug has been fixed, there is no longer a dependency on GTK.
