### ISSUE TITLE
/usr/bin/jasmine gets entered into twice

### ISSUE THREAD

**Issue by smspillaz** [ptomato/jasmine-gjs#20]
For some reason, this is being entered into twice early in the boot process. I'm not sure the exact point where this happens, but it can cause nasty things to happen, like trying to create GI classes twice.

For example (project name redacted):
    smspillaz@endless:~/Source/redacted-project-name$ jasmine
    Gjs-Message: JS LOG: Calling into /usr/bin/jasmine
    Gjs-Message: JS LOG: @/usr/bin/jasmine:9

    Constructed
    Configuration loaded from /home/smspillaz/Source/redacted-project-name/jasmine.json
    Gjs-Message: JS LOG: Calling command.run run@/usr/share/jasmine-gjs/command.js:86
    @/usr/bin/jasmine:53

    Gjs-Message: JS LOG: Parsing options []
    Gjs-Message: JS LOG: parseOptions@/usr/share/jasmine-gjs/options.js:60
    run@/usr/share/jasmine-gjs/command.js:87
    @/usr/bin/jasmine:53

    Gjs-Message: JS LOG: [[],{"color":true}]
    Gjs-Message: JS LOG: Calling into /usr/bin/jasmine
    Gjs-Message: JS LOG: @/usr/bin/jasmine:9

    Constructed
    Configuration loaded from /home/smspillaz/Source/redacted-project-name/jasmine.json
    Gjs-Message: JS LOG: Calling command.run run@/usr/share/jasmine-gjs/command.js:86
    @/usr/bin/jasmine:53

    Gjs-Message: JS LOG: Parsing options ["--verbose","/home/smspillaz/Source/redacted-project-name/tests/js","--no-config"]
    Gjs-Message: JS LOG: parseOptions@/usr/share/jasmine-gjs/options.js:60
    run@/usr/share/jasmine-gjs/command.js:87
    @/usr/bin/jasmine:53

    Gjs-Message: JS LOG: Push file /home/smspillaz/Source/redacted-project-name/tests/js
    Gjs-Message: JS LOG: [["/home/smspillaz/Source/redacted-project-name/tests/js"],{"color":true,"verbose":true,"no-config":true}]
    Gjs-Message: JS LOG: [
      "/home/smspillaz/Source/redacted-project-name/tests/js"
    ]
    Gjs-Message: JS LOG: testRedactedProjectNameTimeline
    Gjs-Message: JS LOG: testRedactedProjectName
    Started

**Comment by ptomato** [comment]
See if the [`launcher-subprocess`](https://github.com/ptomato/jasmine-gjs/tree/launcher-subprocess) branch does anything for you?

**Comment by ptomato** [comment]
This should be fixed now on master.
