### ISSUE TITLE
Warnings with GJS 1.50.1

### ISSUE THREAD

**Issue by elvetemedve** [ptomato/jasmine-gjs#22]
## The problem

I get few warnings with latest GJS.

> (gjs:5886): Gjs-WARNING **: Some code accessed the property 'Jasmine' on the module 'jasmineBoot'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.
> 
> (gjs:5886): Gjs-WARNING **: Some code accessed the property 'ConsoleReporter' on the module 'consoleReporter'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.
> 
> (gjs:5886): Gjs-WARNING **: Some code accessed the property 'VerboseReporter' on the module 'verboseReporter'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.

### Version
Jasmine 2.2.1

### Environment
Arch Linux 4.13.12
Gnome 3.26.2
GJS 1.50.1

**Comment by ptomato** [comment]
I had already fixed this a couple of months ago, but forgot to push the commits. Thank you for the reminder!
