### ISSUE TITLE
It does not return non-zero exit code on test failure

### ISSUE THREAD

**Issue by elvetemedve** [ptomato/jasmine-gjs#23]
## The problem

In case of a failed test, the Jasmine command should exit with a non-zero code according to the UNIX.

Let's suppose we have a failing test case in **spec/test.js** like
```js
describe("A suite is just a function", function() {
    expect(true).toBe(false);
});
```
When I run `jasmine spec/test.js; echo $?` and check the output.

### Actual result
0

### Expected result
Greater than 0.

### Version

Jasmine 2.2.1

### Environment

Arch Linux 4.13.12
Gnome 3.26.2
GJS 1.50.1

**Comment by ptomato** [comment]
Thanks for the report!
