### ISSUE TITLE
All files in include paths are loaded as specs

### ISSUE THREAD

**Issue by bartlibert** [ptomato/jasmine-gjs#37]
Since commit 2fba93e, all javascript files in the include paths are loaded as specs as well, not just the spec paths.

More context, my jasmine.json config is as follows:

```
{
    "include_paths": [
        ".",
        "spec/jsOverride"
    ],
    "spec_files": [
        "spec"
    ],
    "exclude_paths": [
        "spec/jsOverride"
    ]
}
```

This used to work with the older versions of jasmine, and the files in the include_paths were used to search for includes, but they were not loaded as specs. What I see now is that all js files in the include paths are also loaded as specs, which causes issues, because my "." folder includes a "node_modules" subfolder for example, which contains stuff that is only related to my dev environment and certainly is not "jasmine testable".
I tried putting "node_modules/*" in the exclude_paths, but this does not change anything.

**Comment by ptomato** [comment]
Thanks for the report. I believe #39 should fix this.
